name: plume_pdf
description: "Cross-platform Flutter PDF reader with DeepSeek-assisted reading."
publish_to: 'none'
version: 0.1.3+27

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  desktop_drop: ^0.6.0
  file_selector: ^1.0.3
  gpt_markdown:
    path: packages/gpt_markdown
  get: ^4.7.3
  hugeicons: ^1.1.7
  http: ^1.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pdfrx: ^1.3.5
  plume_ai_chat:
    path: packages/plume_ai_chat
  shared_preferences: ^2.5.3
  window_manager: ^0.4.3
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  loading_indicator: ^3.1.1
  super_clipboard: ^0.8.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.13

msix_config:
  display_name: Plume PDF
  publisher_display_name: xiehan
  identity_name: com.xiehan.plumepdf
  msix_version: 0.1.3.0
  logo_path: assets/windows_app_icon_1024.png
  capabilities: internetClient
  file_extension: .pdf

flutter:
  uses-material-design: true

  fonts:
    - family: OPPO Sans
      fonts:
        - asset: assets/fonts/OPPO_Sans_4.0.ttf
    - family: GoogleSansMono
      fonts:
        - asset: assets/fonts/GoogleSansMono-Regular.ttf

  assets:
    - assets/config/
